"""GitHub Copilot CLI agent implementation."""

from typing import Any, Optional

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

from .base_agent import AgentConfig, AgentResponse, AgentType, BaseAgent


class CopilotAgent(BaseAgent):
    """
    GitHub Copilot CLI agent implementation.

    Uses OpenAI API (Copilot backend) for code generation and analysis.
    """

    def __init__(self, config: AgentConfig) -> None:
        """
        Initialize Copilot agent.

        Args:
            config: Agent configuration with Copilot-specific settings
        """
        if OpenAI is None:
            raise ImportError("openai is required for Copilot. Install with: pip install openai")

        if config.agent_type != AgentType.COPILOT:
            config.agent_type = AgentType.COPILOT
        super().__init__(config)

        # Initialize OpenAI client (Copilot uses OpenAI backend)
        self.client = OpenAI(api_key=self.config.api_key)

    def _validate_config(self) -> None:
        """Validate Copilot specific configuration."""
        if not self.config.api_key:
            raise ValueError("OPENAI_API_KEY is required for Copilot")

        # Set default model if not specified
        if not self.config.model:
            self.config.model = "gpt-4-turbo"

    def process_task(self, task: str, context: Optional[dict[str, Any]] = None) -> AgentResponse:
        """
        Process a coding task using Copilot.

        Args:
            task: Task description
            context: Additional context

        Returns:
            AgentResponse with results
        """
        try:
            # Create system prompt
            system_prompt = self.config.system_prompt or (
                "You are GitHub Copilot, a coding assistant following "
                "Test-Driven Development principles. "
                "Provide clear, well-tested code with type hints and documentation."
            )

            # Use OpenAI API (Copilot backend)
            response = self.client.chat.completions.create(
                model=self.config.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": task},
                ],
                max_tokens=self.config.max_tokens,
                temperature=self.config.temperature,
            )

            return AgentResponse(
                success=True,
                message=response.choices[0].message.content or "",
                changes=["Code generated by Copilot"],
                metadata={"model": self.config.model, "context": context or {}},
            )
        except Exception as e:
            return AgentResponse(
                success=False,
                message="Failed to process task",
                error=str(e),
            )

    def fix_ci_errors(self, error_logs: dict[str, str], branch: str) -> AgentResponse:
        """
        Automatically fix CI errors using Copilot.

        Args:
            error_logs: Dictionary of error types to log content
            branch: Git branch name

        Returns:
            AgentResponse with fix results
        """
        try:
            # Combine error logs
            combined_errors = "\n\n".join(
                f"=== {error_type} ===\n{log}" for error_type, log in error_logs.items()
            )

            prompt = f"""Analyze and fix these CI errors:

{combined_errors}

Branch: {branch}

Provide:
1. Root cause analysis
2. Specific code fixes
3. Test updates if needed
4. Prevention strategy

Follow Test-Driven Development principles.
"""

            response = self.client.chat.completions.create(
                model=self.config.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a debugging expert specializing in CI/CD issues.",
                    },
                    {"role": "user", "content": prompt},
                ],
                max_tokens=self.config.max_tokens,
                temperature=self.config.temperature,
            )

            return AgentResponse(
                success=True,
                message=response.choices[0].message.content or "",
                changes=["CI fixes generated by Copilot"],
                metadata={"branch": branch, "error_types": list(error_logs.keys())},
            )
        except Exception as e:
            return AgentResponse(
                success=False,
                message="Failed to fix CI errors",
                error=str(e),
            )

    def review_code(self, diff: str, context: Optional[dict[str, Any]] = None) -> AgentResponse:
        """
        Review code changes using Copilot.

        Args:
            diff: Git diff
            context: Additional context

        Returns:
            AgentResponse with review comments
        """
        try:
            prompt = f"""Review this code change:

```diff
{diff}
```

Context: {context or {}}

Provide detailed code review covering:
1. Code quality and style
2. Potential bugs or issues
3. Performance considerations
4. Security concerns
5. Test coverage
6. Improvement suggestions
"""

            response = self.client.chat.completions.create(
                model=self.config.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a senior code reviewer with expertise in "
                        "software engineering best practices.",
                    },
                    {"role": "user", "content": prompt},
                ],
                max_tokens=self.config.max_tokens,
                temperature=self.config.temperature,
            )

            return AgentResponse(
                success=True,
                message=response.choices[0].message.content or "",
                changes=["Code review by Copilot"],
                metadata={"diff_size": len(diff), "context": context or {}},
            )
        except Exception as e:
            return AgentResponse(
                success=False,
                message="Failed to review code",
                error=str(e),
            )

    def get_capabilities(self) -> dict[str, bool]:
        """Get Copilot specific capabilities."""
        return {
            **super().get_capabilities(),
            "github_integration": True,
            "cli_mode": True,
            "function_calling": True,
            "json_mode": True,
        }
